// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD98eUfsJBjenkM8_eiBJI2fX2cj6OSAQE',
    appId: '1:1052129564127:android:88d509e011729a3863206a',
    messagingSenderId: '1052129564127',
    projectId: 'wallet-9b13f',
    storageBucket: 'wallet-9b13f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDYsP4bRz93ESfpY5GxuhS_NMESAtHRXg',
    appId: '1:1052129564127:ios:d7ea781bf0166aa463206a',
    messagingSenderId: '1052129564127',
    projectId: 'wallet-9b13f',
    storageBucket: 'wallet-9b13f.appspot.com',
    iosClientId: '1052129564127-o0um782c2m3e1jbtk79pn6tdopbh19mt.apps.googleusercontent.com',
    iosBundleId: 'timur.karev.wallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDYsP4bRz93ESfpY5GxuhS_NMESAtHRXg',
    appId: '1:1052129564127:ios:d7ea781bf0166aa463206a',
    messagingSenderId: '1052129564127',
    projectId: 'wallet-9b13f',
    storageBucket: 'wallet-9b13f.appspot.com',
    iosClientId: '1052129564127-o0um782c2m3e1jbtk79pn6tdopbh19mt.apps.googleusercontent.com',
    iosBundleId: 'timur.karev.wallet',
  );
}
